apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-boot-app
  namespace: spring-boot-prod

spec:
  replicas: 1

  selector:
    matchLabels:
      app: spring-boot-app

  template:

    metadata:
      labels:
        app: spring-boot-app

    spec:

      containers:

        - name: spring-boot-app

          image: spring-boot-app:1.0

          imagePullPolicy: Never

          ports:

            - containerPort: 8081


          livenessProbe:

            httpGet:

              path: /actuator/health/liveness

              port: 8081


            initialDelaySeconds: 30

            periodSeconds: 10

            timeoutSeconds: 5

            failureThreshold: 3