apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app

spec:
  containers:
    - name: spring-boot-app
      image: spring-boot-app:1.0
      imagePullPolicy: Never

      ports:
        - containerPort: 8081