apiVersion: v1
kind: Service

metadata:
  name: spring-boot-app-nodeport

spec:
  selector:
    app: spring-boot-app

  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081

  type: NodePort